#10 - CI/CD
viniciuskneves/vue-github-repository-contributions pull request #14
Opened 2019-01-18 01:58 UTC by osmarpetry

Não fiz do teste porque os testes estão todos quebrados, todas sugestão de melhoria de código e boas práticas na hora de resolver a issue são bem vindas!

2019-01-18 19:24 UTC, viniciuskneves requested changes
Ta muito bom mesmo! Só alguns pontos específicos para alterar, mas o grosso já está feito \o/

Valeu!

2019-01-18 19:24 UTC, viniciuskneves commented on .travis.yml
> +  domain: vue-github-repository-contributions-2019.surge.sh
Usa o domain do arquivo `CNAME`

2019-01-18 19:24 UTC, viniciuskneves commented on .travis.yml
> +  - "stable"
"node": https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#specifying-nodejs-versions

2019-01-18 19:24 UTC, viniciuskneves commented on .travis.yml
> +  - yarn lint
Favor manter NPM, projeto não está usando Yarn por default.

2019-01-18 19:24 UTC, viniciuskneves commented on .travis.yml
> +  - yarn lint
Yarn ainda tem uma peculiaridade no cache: https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#caching-with-yarn

2019-01-18 19:24 UTC, viniciuskneves commented on CNAME
> +vue-github-repository-contributions-2019.surge.sh
Restora para o valor antigo, esse 2019 deve ter sido algum teste teu provavelmente.

2019-01-18 19:32 UTC, osmarpetry commented on .travis.yml
> +  - "stable"
Acabei deixando passar isso, vou corrigirem

2019-01-18 19:34 UTC, osmarpetry commented on .travis.yml
> +  - yarn lint
Ainda bem que fiz isso, agora eu devo ficar mais ligado nessa peculiaridade citada com o yarn

2019-01-18 19:37 UTC, osmarpetry commented on CNAME
> +vue-github-repository-contributions-2019.surge.sh
Você tinha dito para criar uma conta no Surge, não consigo usar seu domínio porque não tenho seu login e token

2019-01-18 19:39 UTC, osmarpetry commented on .travis.yml
> +  domain: vue-github-repository-contributions-2019.surge.sh
Erro meu, naquele de não entender porque não estava funcionando e depois não reler o arquivo que achei na internet

2019-01-19 00:42 UTC, osmarpetry commented on .travis.yml
> +  - "stable"
No link que passou, também é feito com `node_js`. Deixar como está na documentação do Travis então?

2019-01-19 01:55 UTC, osmarpetry commented on .travis.yml
> +  domain: vue-github-repository-contributions-2019.surge.sh
Tentei fazer usando o `npm run deploy` pelo Travis mas não consigo, apenas com esse que estava no `.travis.yml`. 

Por mim, eu deixaria assim, apenas mudar o URL para o seu, mas daí eu não tenho seu token ou e-mail para alterar no Travis

2019-01-21 13:54 UTC, viniciuskneves commented on .travis.yml
> +  - "stable"
Me referi ao `stable`

2019-01-21 13:55 UTC, viniciuskneves commented on CNAME
> +vue-github-repository-contributions-2019.surge.sh
Tu crias pra fazer os teus testes e tudo mais. Mas isso não precisa ser comitado, porque não precisa ser alterado no repositório principal, saca?

2019-01-21 14:54 UTC, osmarpetry commented on CNAME
> +vue-github-repository-contributions-2019.surge.sh
Sim, quanto ao `.travis.yml`? Maneira que deu certo, foi deixar tudo por lá sem esse arquivo CNAME

2019-01-21 23:19 UTC, viniciuskneves requested changes
Corrige aquele último ponto (sim, vai quebrar a imagem até eu mergear) e remove `yarn.lock` que aí mandamos bala!

2019-01-21 23:19 UTC, viniciuskneves commented on README.md
> +![build-travis](https://travis-ci.com/osmarpetry/vue-github-repository-contributions.svg?branch=master)
Aqui tais colocando a tua badge e não a do projeto original.

2020-11-21 21:35 UTC, closed without merging